version: '3'

services:
  app:
    build: BUILD
    image: secure-ws
    container_name: secure-ws
    restart: always
    volumes:
      - ./volumes/app:/opt/secure-ws
      - ./volumes/ssl/secure-ws.cobblepot59.int.crt:/etc/ssl/certs/secure-ws.cobblepot59.int.crt:ro
      - ./volumes/ssl/secure-ws.cobblepot59.int.key:/etc/ssl/private/secure-ws.cobblepot59.int.key:ro
    environment:
      - PYTHONUNBUFFERED=1

  rp:
    image: nginx:alpine
    container_name: secure-ws-rp
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./volumes/rp/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./volumes/ssl/secure-ws.cobblepot59.int.crt:/etc/ssl/certs/secure-ws.cobblepot59.int.crt:ro
      - ./volumes/ssl/secure-ws.cobblepot59.int.key:/etc/ssl/private/secure-ws.cobblepot59.int.key:ro
    environment:
      - NGINX_HOST=secure-ws.cobblepot59.int
